name: Install Composer Dependencies
description: Install Composer dependencies
inputs:
  dev:
    description: Install development dependencies
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Composer Cache
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

    - name: Composer Install
      id: composer-install
      uses: docker://nanacoma/php-test:6.0.1
      with:
        options: -v ${{ github.workspace }}:/app
        entrypoint: ["composer", "install"]
#      if: steps.composer-cache.output.cache-hit != 'true'