name: Install Composer Dependencies
description: Install Composer dependencies
inputs:
  dev:
    description: Install development dependencies
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Composer Cache
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: /root/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

    - name: Vendor Cache
      id: vendor-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-vendor-${{ hashFiles('composer.lock') }}-dev-${{ inputs.dev }}

    - name: Composer Install
      id: composer-install
      uses: ./.github/actions/php
      with:
        command: composer
        args: install --no-dev
      if: steps.composer-cache.output.cache-hit != 'true' && inputs.dev != 'true'

    - name: Composer Dev Install
      id: composer-install-dev
      uses: ./.github/actions/php
      with:
        command: composer
        args: install
      if: steps.composer-cache.output.cache-hit != 'true' && inputs.dev != 'false'
