version: '3.7'

services:
  app:
    image: www
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: app
    hostname: test-app
    environment:
      APP_KEY: "base64:YS/ok7lBEiTQhUvUMSYSsRev5YssnMOwSlwjgRAmqXU="
    volumes:
      - .:/app
  proxy:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    container_name: proxy
    hostname: proxy
    ports:
      - '9005:9005'
    depends_on:
      - app
    volumes:
      - .:/app
      - .deploy/development/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - app:app