name: PHP
description: Run php (composer, phpunit, etc) actions in the container environment.
inputs:
  command:
    description: The command you want to run (composer, ./vendor/bin/phpunit)
    required: true
  args:
    description: Optional arguments passed to the command.
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: php
      id: php
      uses: docker://nanacoma/php-test:6.0.1
      with:
        entrypoint: ${{ inputs.command }}
        args: ${{ inputs.args }}
