name: PHPUnit
description: Run PHPUnit on the code base.
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      name: PHPUnit Cache
      id: phpunit-cache
      with:
        path: .phpunit.cache
        key: ${{ runner.os }}-modules-${{ hashFiles('composer.lock', 'phpstan.neon' }}
    - name: PHPUnit
      id: phpunit
      uses: ./.github/actions/php
      with:
        command: ./vendor/bin/phpunit