name: PHPStan
description: Run PHPStan on the code base.
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      name: PHPStan Cache
      id: phpstan-cache
      with:
        path: .phpstan
        key: ${{ runner.os }}-modules-${{ hashFiles('composer.lock', 'phpstan.neon') }}
    - name: PHPStan
      id: phpstan
      uses: ./.github/actions/php
      with:
        command: ./vendor/bin/phpstan