name: CI

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-composer-deps
        name: Run Composer Install
        with:
          dev: true

  phpunit:
    name: PHPUnit
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::121952031047:role/github-deploy-php

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: ./.github/actions/install-composer-deps
        with:
          dev: true
        name: Composer Install

      - uses: ./.github/actions/phpunit
        name: Run PHPUnit

  phpstan:
    name: PHPStan
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::121952031047:role/github-deploy-php

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@v3

      - uses: ./.github/actions/install-composer-deps
        with:
          dev: true
        name: Composer Install

      - uses: ./.github/actions/phpstan
        name: Run PHPStan






