name: CI

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nanacoma/php-test
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-composer-deps





