name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-composer-deps
        name: Composer Install
        with:
          dev: true
      - uses: ./.github/actions/phpunit
        name: PHPUnit
      - uses: ./.github/actions/phpstan
        name: PHPStan





