name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/preload-php-container

      - uses: ./.github/actions/install-composer-deps
        name: Run Composer Install
        with:
          dev: true

  phpunit:
    name: PHPUnit
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/preload-php-container

      - uses: ./.github/actions/install-composer-deps
        with:
          dev: true
        name: Composer Install

      - uses: ./.github/actions/phpunit
        name: Run PHPUnit

  phpstan:
    name: PHPStan
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/preload-php-container

      - uses: ./.github/actions/install-composer-deps
        with:
          dev: true
        name: Composer Install

      - uses: ./.github/actions/phpstan
        name: Run PHPStan






