name: CI
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nanacoma/app-test:${{ steps.vars.outputs.tag }}
          build-args: |
            "APP_ENV=${{ steps.vars.outputs.tag }}"
