name: CI
on:
  push:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Version bump
        id: version-bump
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          namespace: "marketing"